name: Publish omero-bifrost to PyPI
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out source-code repository

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install .

      - name: Build the distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: github.repository == 'qbicpkgs/omero-bifrost'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
